name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    defaults:
      run:
        working-directory: ./nodejs-rest-client

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended
        # for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install libraries
      run: yarn install

    - name: Run linting
      run: yarn lint

    - name: Build application
      run: yarn build

    - name: Run unit tests
      run: yarn test:unit:coverage

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - uses: satackey/action-docker-layer-caching@v0.0.8
    - name: Push docker images
      run: |
        docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker-compose build
        docker-compose push
        docker logout
