name: Unit Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]
        
    defaults:
      run:
        working-directory: ./nodejs-rest-client

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests and linting
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn lint
    - run: yarn build
    - run: yarn test:unit
      


